language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache
        - .travis/downloads
        - .travis/ffmpeg-release-64bit-static

before_install:
  - |
    if [ "x$REMOVE_QA" = "xyes" ]; then
      composer remove vimeo/psalm infection/infection friendsofphp/php-cs-fixer phpstan/phpstan-symfony phpstan/phpstan-webmozart-assert phpstan/phpstan phpstan/phpstan-phpunit phpstan/phpstan-strict-rules --dev --no-interaction $COMPOSER_ARGS;
    fi
  - |
    if [ "x$XDEBUG" != "xyes" ]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
    fi
  - |
    if [ "x$INSTALL_FFMPEG" == "xyes" ]; then
      .travis/travis-install-ffmpeg.sh
    fi

install:
  - |
    if [[ "x$DEPS" == "xlowest" ]]; then
      travis_retry composer -n update --prefer-dist --prefer-lowest --prefer-stable --no-interaction $COMPOSER_ARGS;
    else
      travis_retry composer -n update --prefer-dist --no-interaction $COMPOSER_ARGS;
    fi
jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Tests
      php: 7.3
      env: XDEBUG=yes INSTALL_FFMPEG=yes REMOVE_QA=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        - bash <(curl -s https://codecov.io/bash)

    - stage: Tests
      php: 7.2
      env: INSTALL_FFMPEG=yes DEPS=lowest REMOVE_QA=yes
      script:
        - composer remove phpunit/phpunit
        - composer require --dev phpunit/phpunit
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml

    - stage: Tests
      php: 7.1
      env: INSTALL_FFMPEG=yes DEPS=lowest REMOVE_QA=yes
      script:
        - composer remove phpunit/phpunit
        - composer require --dev phpunit/phpunit
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml

    - stage: Tests
      php: nightly
      env: COMPOSER_ARGS=--ignore-platform-reqs REMOVE_QA=yes
      script:
        - ./vendor/bin/phpunit --testsuite unit -v -c .travis/phpunit.xml


    - stage: PHPStan, Psalm and Code style
      php: 7.3
      env: XDEBUG=no INSTALL_FFMPEG=no REMOVE_QA=no
      script:
        - composer phpstan
        - composer psalm
        - composer cs-check


