site_name: 'mediatools-cli'
site_description: 'soluble-mediatools-cli documentation'
site_author: 'Sébastien Vanvelthem'
site_url: https://soluble-io.github.io/soluble-mediatools

# Repository
repo_name: 'soluble-mediatools-cli'
repo_url: 'https://github.com/soluble-io/soluble-mediatools-cli'

# Copyright
copyright: 'Copyright &copy; 2018-2019 Sébastien Vanvelthem'

strict: true

docs_dir: docs
site_dir: build/docs

nav:
    - Home: index.md
    - License: 'about/license.md'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'orange'
  font:
    text: 'Lato'
    code: 'Roboto Mono'
  logo: logo
  feature:
    tabs: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/soluble-io/soluble-mediatools-cli'

extra_css:
  - 'assets/css/extra.css'
  - 'assets/css/monokai.css'

#google_analytics:
  #- ''
  #- 'auto'


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
